# Generated by Django 4.2.23 on 2025-07-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('tipo', models.CharField(choices=[('bom', 'bom'), ('ruim', 'ruim')], max_length=50)),
                ('data_acontecimento', models.DateTimeField(verbose_name='Data do Acontecimento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
