# Generated by Django 4.2.23 on 2025-07-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('pscicologo', 'Pscicólogo')], default='user', max_length=50),
        ),
    ]
